export const LocalDictCollection = {
  grammatic: [
    [ /total/gi, '' ],
    [ /reported/gi, '' ],
    [ /currency/gi, 'curr' ],
    [ /fiscal date ending/gi, 'date' ],
  ],
  balances: [
    [ /accounts/gi, 'acc' ],
    [ /currr?ent/gi, 'c' ],
    [ /noncurrent/gi, 'nc' ],
    [ /retained/gi, 'ret' ],
    [ /earnings/gi, 'e' ],
    [ /short/gi, 's' ],
    [ /long/gi, 'l' ],
    [ /stock/gi, 'sto' ],
    [ /treasury/gi, 'tr' ],
    [ /common/gi, 'cm' ],
    [ /accumulated/gi, 'accum' ],
    [ /lease/gi, 'leas' ],
    [ /obligations?/gi, 'ob' ],
    [ /at carrying value/gi, '' ],
    [ /property plant equipment/, 'ppe' ],
    [ /shares outstanding/g, 'so' ]
  ],
  incomes: [
    [ /selling/gi, 's' ],
    [ /general/gi, 'g' ],
    [ /administrative/gi, 'a' ],
    [ /research/gi, 'r' ],
    [ /development/gi, 'd' ],
    [ /continuing/gi, 'c' ],
    [ /operations?/gi, 'op' ],
    [ /cost ?(of)?/gi, 'c' ],
    [ /gross/gi, 'g' ],
    [ /services/gi, 's' ],
    [ /goods/gi, 'g' ]
  ],
  cashflows: [
    [ /cashflow/gi, 'cf' ],
    [ /proceeds/gi, 'proc' ],
    [ /repurchase/gi, 'rp' ],
    [ /activities/gi, 'act' ],
    [ /payout/gi, 'pyo' ],
    [ /issuance/gi, 'isu' ],
    [ /securities/gi, 'sec' ],
    [ /common/gi, 'c' ],
    [ /stock/gi, 'sto' ],
    [ /depletion/gi, 'dpl' ],
    [ /treasury/gi, 'tr' ],
  ],
}