export const cashflowsDb = [
  [                                                   'symbol',                     'symbol'],
  [                                         'fiscalDateEnding',                       'date'],
  [                                         'reportedCurrency',                       'curr'],
  [                                        'operatingCashflow',                       'opCf'],
  [                           'paymentsForOperatingActivities',                 'pmForOpAct'],
  [                          'proceedsFromOperatingActivities',                'procFrOpAct'],
  [                             'changeInOperatingLiabilities',                 'chInOpLiab'],
  [                                  'changeInOperatingAssets',                  'chInOpAst'],
  [                     'depreciationDepletionAndAmortization',                 'deprDplAmo'],
  [                                      'capitalExpenditures',                    'capExpd'],
  [                                      'changeInReceivables',                   'chInRecv'],
  [                                        'changeInInventory',                   'chInInvt'],
  [                                               'profitLoss',                    'pftLoss'],
  [                                   'cashflowFromInvestment',                     'cfFrIv'],
  [                                    'cashflowFromFinancing',                    'cfFrFin'],
  [                    'proceedsFromRepaymentsOfShortTermDebt',         'procFrRepmOfStDebt'],
  [                       'paymentsForRepurchaseOfCommonStock',              'pmForRpOfCSto'],
  [                            'paymentsForRepurchaseOfEquity',               'pmForRpOfEqt'],
  [                    'paymentsForRepurchaseOfPreferredStock',           'pmForRpOfPrefSto'],
  [                                           'dividendPayout',                     'divPyo'],
  [                                'dividendPayoutCommonStock',                 'divPyoCSto'],
  [                             'dividendPayoutPreferredStock',              'divPyoPrefSto'],
  [                        'proceedsFromIssuanceOfCommonStock',            'procFrIsuOfCSto'],
  ['proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet', 'procFrIsuOfLtDebtCapSecNet'],
  [                     'proceedsFromIssuanceOfPreferredStock',         'procFrIsuOfPrefSto'],
  [                           'proceedsFromRepurchaseOfEquity',              'procFrRpOfEqt'],
  [                          'proceedsFromSaleOfTreasuryStock',          'procFrSaleOfTrSto'],
  [                           'changeInCashAndCashEquivalents',                    'chInCce'],
  [                                     'changeInExchangeRate',                 'chInExRate'],
  [                                                'netIncome',                     'netInc'],
]