export const incomesDb = [
  [                           'symbol',          'symbol'],
  [                 'fiscalDateEnding',            'date'],
  [                 'reportedCurrency',            'curr'],
  [                      'grossProfit',            'gPft'],
  [                     'totalRevenue',             'rev'],
  [                    'costOfRevenue',            'cRev'],
  [       'costofGoodsAndServicesSold',            'cGSv'],
  [                  'operatingIncome',           'opInc'],
  [  'sellingGeneralAndAdministrative',             'sGA'],
  [           'researchAndDevelopment',              'rD'],
  [                'operatingExpenses',           'opExp'],
  [              'investmentIncomeNet',        'ivIncNet'],
  [                'netInterestIncome',      'netIntrInc'],
  [                   'interestIncome',         'intrInc'],
  [                  'interestExpense',         'intrExp'],
  [                'nonInterestIncome',        'nintrInc'],
  [          'otherNonOperatingIncome',         'oNopInc'],
  [                     'depreciation',            'depr'],
  [      'depreciationAndAmortization',         'deprAmo'],
  [                  'incomeBeforeTax',     'incBeforeTx'],
  [                 'incomeTaxExpense',        'incTxExp'],
  [           'interestAndDebtExpense',     'intrDebtExp'],
  ['netIncomeFromContinuingOperations',     'netIncFrCOp'],
  [      'comprehensiveIncomeNetOfTax', 'comprIncNetOfTx'],
  [                             'ebit',            'ebit'],
  [                           'ebitda',          'ebitda'],
  [                        'netIncome',          'netInc'],
]